# Generated by Django 3.2.2 on 2021-06-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customauth',
            name='otp',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customauth',
            name='mobile_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
