# Generated by Django 3.2.2 on 2021-06-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210614_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
